name: Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    name: Formatting & Clippy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Rustfmt Check
        run: cargo fmt --all -- --check

      - name: Clippy Check
        run: cargo clippy -- -D warnings

  test:
    name: Build Frontend & Backend
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check Frontend
        working-directory: web
        run: |
          npm ci
          npm run build

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check Backend
        run: cargo check --release
